//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcitas.WSAPCBot {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/WS_ref_APC/ServiceConsult_APC", ConfigurationName="WSAPCBot.WSAPCbotSoap")]
    public interface WSAPCbotSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/BAC_APC_WS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BAC_APC_WS(int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/BAC_APC_WS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BAC_APC_WSAsync(int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/APC_WS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet APC_WS(int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/APC_WS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> APC_WSAsync(int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/BAC_APC_WS_S3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BAC_APC_WS_S3(int forzar_consulta, int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/BAC_APC_WS_S3", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BAC_APC_WS_S3Async(int forzar_consulta, int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/BAC_APC_ScorePi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BAC_APC_ScorePi(string id_cli, int type_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/BAC_APC_ScorePi", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BAC_APC_ScorePiAsync(string id_cli, int type_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/BAC_APC_Historia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BAC_APC_Historia(string id_cli, int type_cli, string user, int app, int referencia1, string referencia2, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_ref_APC/ServiceConsult_APC/BAC_APC_Historia", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BAC_APC_HistoriaAsync(string id_cli, int type_cli, string user, int app, int referencia1, string referencia2, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAPCbotSoapChannel : appcitas.WSAPCBot.WSAPCbotSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAPCbotSoapClient : System.ServiceModel.ClientBase<appcitas.WSAPCBot.WSAPCbotSoap>, appcitas.WSAPCBot.WSAPCbotSoap {
        
        public WSAPCbotSoapClient() {
        }
        
        public WSAPCbotSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAPCbotSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAPCbotSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAPCbotSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet BAC_APC_WS(int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.BAC_APC_WS(type_cli, id_cli, user, app, referencia1, referencia2, token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BAC_APC_WSAsync(int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.BAC_APC_WSAsync(type_cli, id_cli, user, app, referencia1, referencia2, token);
        }
        
        public System.Data.DataSet APC_WS(int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.APC_WS(type_cli, id_cli, user, app, referencia1, referencia2, token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> APC_WSAsync(int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.APC_WSAsync(type_cli, id_cli, user, app, referencia1, referencia2, token);
        }
        
        public string BAC_APC_WS_S3(int forzar_consulta, int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.BAC_APC_WS_S3(forzar_consulta, type_cli, id_cli, user, app, referencia1, referencia2, token);
        }
        
        public System.Threading.Tasks.Task<string> BAC_APC_WS_S3Async(int forzar_consulta, int type_cli, string id_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.BAC_APC_WS_S3Async(forzar_consulta, type_cli, id_cli, user, app, referencia1, referencia2, token);
        }
        
        public string BAC_APC_ScorePi(string id_cli, int type_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.BAC_APC_ScorePi(id_cli, type_cli, user, app, referencia1, referencia2, token);
        }
        
        public System.Threading.Tasks.Task<string> BAC_APC_ScorePiAsync(string id_cli, int type_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.BAC_APC_ScorePiAsync(id_cli, type_cli, user, app, referencia1, referencia2, token);
        }
        
        public string BAC_APC_Historia(string id_cli, int type_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.BAC_APC_Historia(id_cli, type_cli, user, app, referencia1, referencia2, token);
        }
        
        public System.Threading.Tasks.Task<string> BAC_APC_HistoriaAsync(string id_cli, int type_cli, string user, int app, int referencia1, string referencia2, string token) {
            return base.Channel.BAC_APC_HistoriaAsync(id_cli, type_cli, user, app, referencia1, referencia2, token);
        }
    }
}
