// <auto-generated />
namespace appcitas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SGRC_Combo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SGRC_Combo));
        
        string IMigrationMetadata.Id
        {
            get { return "201903051805540_SGRC_Combo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
