//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace appcitas.CitasAutoservicioWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CitasAutoservicioWSSoap", Namespace="http://tempuri.org/")]
    public partial class CitasAutoservicioWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarListasDeConfiguracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarTiposRazonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCentrosDeAtencionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCentrosDeAtencionPorSegmentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarHorariosDeAtencionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarSucursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCitaPorTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCitaPorTarjetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarCitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearCitaWalkInOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearCitaProgramadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarEmailCitaProgramadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPorTarjetaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CitasAutoservicioWS() {
            this.Url = global::appcitas.Properties.Settings.Default.appcitas_CitasAutoservicioWS_CitasAutoservicioWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarListasDeConfiguracionCompletedEventHandler ConsultarListasDeConfiguracionCompleted;
        
        /// <remarks/>
        public event ConsultarTiposRazonCompletedEventHandler ConsultarTiposRazonCompleted;
        
        /// <remarks/>
        public event ConsultarCentrosDeAtencionCompletedEventHandler ConsultarCentrosDeAtencionCompleted;
        
        /// <remarks/>
        public event ConsultarCentrosDeAtencionPorSegmentoCompletedEventHandler ConsultarCentrosDeAtencionPorSegmentoCompleted;
        
        /// <remarks/>
        public event ConsultarHorariosDeAtencionCompletedEventHandler ConsultarHorariosDeAtencionCompleted;
        
        /// <remarks/>
        public event ConsultarSucursalCompletedEventHandler ConsultarSucursalCompleted;
        
        /// <remarks/>
        public event ConsultarCitaPorTicketCompletedEventHandler ConsultarCitaPorTicketCompleted;
        
        /// <remarks/>
        public event ConsultarCitaPorTarjetaCompletedEventHandler ConsultarCitaPorTarjetaCompleted;
        
        /// <remarks/>
        public event ConfirmarCitaCompletedEventHandler ConfirmarCitaCompleted;
        
        /// <remarks/>
        public event CrearCitaWalkInCompletedEventHandler CrearCitaWalkInCompleted;
        
        /// <remarks/>
        public event CrearCitaProgramadaCompletedEventHandler CrearCitaProgramadaCompleted;
        
        /// <remarks/>
        public event EnviarEmailCitaProgramadaCompletedEventHandler EnviarEmailCitaProgramadaCompleted;
        
        /// <remarks/>
        public event EnviarEmailCompletedEventHandler EnviarEmailCompleted;
        
        /// <remarks/>
        public event ConsultarPorTarjetaCompletedEventHandler ConsultarPorTarjetaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarListasDeConfiguracion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConfigItemDTO[] ConsultarListasDeConfiguracion(string token) {
            object[] results = this.Invoke("ConsultarListasDeConfiguracion", new object[] {
                        token});
            return ((ConfigItemDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarListasDeConfiguracionAsync(string token) {
            this.ConsultarListasDeConfiguracionAsync(token, null);
        }
        
        /// <remarks/>
        public void ConsultarListasDeConfiguracionAsync(string token, object userState) {
            if ((this.ConsultarListasDeConfiguracionOperationCompleted == null)) {
                this.ConsultarListasDeConfiguracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarListasDeConfiguracionOperationCompleted);
            }
            this.InvokeAsync("ConsultarListasDeConfiguracion", new object[] {
                        token}, this.ConsultarListasDeConfiguracionOperationCompleted, userState);
        }
        
        private void OnConsultarListasDeConfiguracionOperationCompleted(object arg) {
            if ((this.ConsultarListasDeConfiguracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarListasDeConfiguracionCompleted(this, new ConsultarListasDeConfiguracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarTiposRazon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TipoRazonDTO[] ConsultarTiposRazon(string token) {
            object[] results = this.Invoke("ConsultarTiposRazon", new object[] {
                        token});
            return ((TipoRazonDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarTiposRazonAsync(string token) {
            this.ConsultarTiposRazonAsync(token, null);
        }
        
        /// <remarks/>
        public void ConsultarTiposRazonAsync(string token, object userState) {
            if ((this.ConsultarTiposRazonOperationCompleted == null)) {
                this.ConsultarTiposRazonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarTiposRazonOperationCompleted);
            }
            this.InvokeAsync("ConsultarTiposRazon", new object[] {
                        token}, this.ConsultarTiposRazonOperationCompleted, userState);
        }
        
        private void OnConsultarTiposRazonOperationCompleted(object arg) {
            if ((this.ConsultarTiposRazonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarTiposRazonCompleted(this, new ConsultarTiposRazonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCentrosDeAtencion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SucursalDTO[] ConsultarCentrosDeAtencion(string token) {
            object[] results = this.Invoke("ConsultarCentrosDeAtencion", new object[] {
                        token});
            return ((SucursalDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCentrosDeAtencionAsync(string token) {
            this.ConsultarCentrosDeAtencionAsync(token, null);
        }
        
        /// <remarks/>
        public void ConsultarCentrosDeAtencionAsync(string token, object userState) {
            if ((this.ConsultarCentrosDeAtencionOperationCompleted == null)) {
                this.ConsultarCentrosDeAtencionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCentrosDeAtencionOperationCompleted);
            }
            this.InvokeAsync("ConsultarCentrosDeAtencion", new object[] {
                        token}, this.ConsultarCentrosDeAtencionOperationCompleted, userState);
        }
        
        private void OnConsultarCentrosDeAtencionOperationCompleted(object arg) {
            if ((this.ConsultarCentrosDeAtencionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCentrosDeAtencionCompleted(this, new ConsultarCentrosDeAtencionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCentrosDeAtencionPorSegmento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SucursalDTO[] ConsultarCentrosDeAtencionPorSegmento(string token, string segmentoId) {
            object[] results = this.Invoke("ConsultarCentrosDeAtencionPorSegmento", new object[] {
                        token,
                        segmentoId});
            return ((SucursalDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCentrosDeAtencionPorSegmentoAsync(string token, string segmentoId) {
            this.ConsultarCentrosDeAtencionPorSegmentoAsync(token, segmentoId, null);
        }
        
        /// <remarks/>
        public void ConsultarCentrosDeAtencionPorSegmentoAsync(string token, string segmentoId, object userState) {
            if ((this.ConsultarCentrosDeAtencionPorSegmentoOperationCompleted == null)) {
                this.ConsultarCentrosDeAtencionPorSegmentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCentrosDeAtencionPorSegmentoOperationCompleted);
            }
            this.InvokeAsync("ConsultarCentrosDeAtencionPorSegmento", new object[] {
                        token,
                        segmentoId}, this.ConsultarCentrosDeAtencionPorSegmentoOperationCompleted, userState);
        }
        
        private void OnConsultarCentrosDeAtencionPorSegmentoOperationCompleted(object arg) {
            if ((this.ConsultarCentrosDeAtencionPorSegmentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCentrosDeAtencionPorSegmentoCompleted(this, new ConsultarCentrosDeAtencionPorSegmentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarHorariosDeAtencion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HorarioDTO[] ConsultarHorariosDeAtencion(string token, int sucursalId, System.DateTime fecha) {
            object[] results = this.Invoke("ConsultarHorariosDeAtencion", new object[] {
                        token,
                        sucursalId,
                        fecha});
            return ((HorarioDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarHorariosDeAtencionAsync(string token, int sucursalId, System.DateTime fecha) {
            this.ConsultarHorariosDeAtencionAsync(token, sucursalId, fecha, null);
        }
        
        /// <remarks/>
        public void ConsultarHorariosDeAtencionAsync(string token, int sucursalId, System.DateTime fecha, object userState) {
            if ((this.ConsultarHorariosDeAtencionOperationCompleted == null)) {
                this.ConsultarHorariosDeAtencionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarHorariosDeAtencionOperationCompleted);
            }
            this.InvokeAsync("ConsultarHorariosDeAtencion", new object[] {
                        token,
                        sucursalId,
                        fecha}, this.ConsultarHorariosDeAtencionOperationCompleted, userState);
        }
        
        private void OnConsultarHorariosDeAtencionOperationCompleted(object arg) {
            if ((this.ConsultarHorariosDeAtencionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarHorariosDeAtencionCompleted(this, new ConsultarHorariosDeAtencionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarSucursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SucursalDTO ConsultarSucursal(string token, int sucursalId) {
            object[] results = this.Invoke("ConsultarSucursal", new object[] {
                        token,
                        sucursalId});
            return ((SucursalDTO)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarSucursalAsync(string token, int sucursalId) {
            this.ConsultarSucursalAsync(token, sucursalId, null);
        }
        
        /// <remarks/>
        public void ConsultarSucursalAsync(string token, int sucursalId, object userState) {
            if ((this.ConsultarSucursalOperationCompleted == null)) {
                this.ConsultarSucursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarSucursalOperationCompleted);
            }
            this.InvokeAsync("ConsultarSucursal", new object[] {
                        token,
                        sucursalId}, this.ConsultarSucursalOperationCompleted, userState);
        }
        
        private void OnConsultarSucursalOperationCompleted(object arg) {
            if ((this.ConsultarSucursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarSucursalCompleted(this, new ConsultarSucursalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCitaPorTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CitaDTO ConsultarCitaPorTicket(string token, string numeroTicket, int sucursalId) {
            object[] results = this.Invoke("ConsultarCitaPorTicket", new object[] {
                        token,
                        numeroTicket,
                        sucursalId});
            return ((CitaDTO)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCitaPorTicketAsync(string token, string numeroTicket, int sucursalId) {
            this.ConsultarCitaPorTicketAsync(token, numeroTicket, sucursalId, null);
        }
        
        /// <remarks/>
        public void ConsultarCitaPorTicketAsync(string token, string numeroTicket, int sucursalId, object userState) {
            if ((this.ConsultarCitaPorTicketOperationCompleted == null)) {
                this.ConsultarCitaPorTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCitaPorTicketOperationCompleted);
            }
            this.InvokeAsync("ConsultarCitaPorTicket", new object[] {
                        token,
                        numeroTicket,
                        sucursalId}, this.ConsultarCitaPorTicketOperationCompleted, userState);
        }
        
        private void OnConsultarCitaPorTicketOperationCompleted(object arg) {
            if ((this.ConsultarCitaPorTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCitaPorTicketCompleted(this, new ConsultarCitaPorTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCitaPorTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CitaDTO ConsultarCitaPorTarjeta(string token, string numeroTarjeta, int sucursalId) {
            object[] results = this.Invoke("ConsultarCitaPorTarjeta", new object[] {
                        token,
                        numeroTarjeta,
                        sucursalId});
            return ((CitaDTO)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCitaPorTarjetaAsync(string token, string numeroTarjeta, int sucursalId) {
            this.ConsultarCitaPorTarjetaAsync(token, numeroTarjeta, sucursalId, null);
        }
        
        /// <remarks/>
        public void ConsultarCitaPorTarjetaAsync(string token, string numeroTarjeta, int sucursalId, object userState) {
            if ((this.ConsultarCitaPorTarjetaOperationCompleted == null)) {
                this.ConsultarCitaPorTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCitaPorTarjetaOperationCompleted);
            }
            this.InvokeAsync("ConsultarCitaPorTarjeta", new object[] {
                        token,
                        numeroTarjeta,
                        sucursalId}, this.ConsultarCitaPorTarjetaOperationCompleted, userState);
        }
        
        private void OnConsultarCitaPorTarjetaOperationCompleted(object arg) {
            if ((this.ConsultarCitaPorTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCitaPorTarjetaCompleted(this, new ConsultarCitaPorTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarCita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskStatus ConfirmarCita(string token, string numeroTicket) {
            object[] results = this.Invoke("ConfirmarCita", new object[] {
                        token,
                        numeroTicket});
            return ((TaskStatus)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarCitaAsync(string token, string numeroTicket) {
            this.ConfirmarCitaAsync(token, numeroTicket, null);
        }
        
        /// <remarks/>
        public void ConfirmarCitaAsync(string token, string numeroTicket, object userState) {
            if ((this.ConfirmarCitaOperationCompleted == null)) {
                this.ConfirmarCitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarCitaOperationCompleted);
            }
            this.InvokeAsync("ConfirmarCita", new object[] {
                        token,
                        numeroTicket}, this.ConfirmarCitaOperationCompleted, userState);
        }
        
        private void OnConfirmarCitaOperationCompleted(object arg) {
            if ((this.ConfirmarCitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarCitaCompleted(this, new ConfirmarCitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearCitaWalkIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CitaDTO CrearCitaWalkIn(
                    string token, 
                    string citaIdentificacion, 
                    string citaNombre, 
                    string citaCorreoElectronico, 
                    string citaTelefonoCelular, 
                    string citaTelefonoOficina, 
                    string citaTelefonoCasa, 
                    string citaTarjeta, 
                    string citaCuenta, 
                    int tramiteId, 
                    int prioridadId, 
                    int sucursalId, 
                    int sucursalIdReferido, 
                    string citaSegmentoId, 
                    string citaEstado, 
                    int citaTipo, 
                    int emisorId, 
                    string usuarioCreacion, 
                    bool permiteTodoSegmento) {
            object[] results = this.Invoke("CrearCitaWalkIn", new object[] {
                        token,
                        citaIdentificacion,
                        citaNombre,
                        citaCorreoElectronico,
                        citaTelefonoCelular,
                        citaTelefonoOficina,
                        citaTelefonoCasa,
                        citaTarjeta,
                        citaCuenta,
                        tramiteId,
                        prioridadId,
                        sucursalId,
                        sucursalIdReferido,
                        citaSegmentoId,
                        citaEstado,
                        citaTipo,
                        emisorId,
                        usuarioCreacion,
                        permiteTodoSegmento});
            return ((CitaDTO)(results[0]));
        }
        
        /// <remarks/>
        public void CrearCitaWalkInAsync(
                    string token, 
                    string citaIdentificacion, 
                    string citaNombre, 
                    string citaCorreoElectronico, 
                    string citaTelefonoCelular, 
                    string citaTelefonoOficina, 
                    string citaTelefonoCasa, 
                    string citaTarjeta, 
                    string citaCuenta, 
                    int tramiteId, 
                    int prioridadId, 
                    int sucursalId, 
                    int sucursalIdReferido, 
                    string citaSegmentoId, 
                    string citaEstado, 
                    int citaTipo, 
                    int emisorId, 
                    string usuarioCreacion, 
                    bool permiteTodoSegmento) {
            this.CrearCitaWalkInAsync(token, citaIdentificacion, citaNombre, citaCorreoElectronico, citaTelefonoCelular, citaTelefonoOficina, citaTelefonoCasa, citaTarjeta, citaCuenta, tramiteId, prioridadId, sucursalId, sucursalIdReferido, citaSegmentoId, citaEstado, citaTipo, emisorId, usuarioCreacion, permiteTodoSegmento, null);
        }
        
        /// <remarks/>
        public void CrearCitaWalkInAsync(
                    string token, 
                    string citaIdentificacion, 
                    string citaNombre, 
                    string citaCorreoElectronico, 
                    string citaTelefonoCelular, 
                    string citaTelefonoOficina, 
                    string citaTelefonoCasa, 
                    string citaTarjeta, 
                    string citaCuenta, 
                    int tramiteId, 
                    int prioridadId, 
                    int sucursalId, 
                    int sucursalIdReferido, 
                    string citaSegmentoId, 
                    string citaEstado, 
                    int citaTipo, 
                    int emisorId, 
                    string usuarioCreacion, 
                    bool permiteTodoSegmento, 
                    object userState) {
            if ((this.CrearCitaWalkInOperationCompleted == null)) {
                this.CrearCitaWalkInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearCitaWalkInOperationCompleted);
            }
            this.InvokeAsync("CrearCitaWalkIn", new object[] {
                        token,
                        citaIdentificacion,
                        citaNombre,
                        citaCorreoElectronico,
                        citaTelefonoCelular,
                        citaTelefonoOficina,
                        citaTelefonoCasa,
                        citaTarjeta,
                        citaCuenta,
                        tramiteId,
                        prioridadId,
                        sucursalId,
                        sucursalIdReferido,
                        citaSegmentoId,
                        citaEstado,
                        citaTipo,
                        emisorId,
                        usuarioCreacion,
                        permiteTodoSegmento}, this.CrearCitaWalkInOperationCompleted, userState);
        }
        
        private void OnCrearCitaWalkInOperationCompleted(object arg) {
            if ((this.CrearCitaWalkInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearCitaWalkInCompleted(this, new CrearCitaWalkInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearCitaProgramada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CitaDTO CrearCitaProgramada(
                    string token, 
                    string citaIdentificacion, 
                    string citaNombre, 
                    string citaCorreoElectronico, 
                    string citaTelefonoCelular, 
                    string citaTelefonoOficina, 
                    string citaTelefonoCasa, 
                    System.DateTime citaFecha, 
                    System.DateTime citaHora, 
                    string citaTarjeta, 
                    string citaCuenta, 
                    int tramiteId, 
                    int sucursalId, 
                    string citaSegmentoId, 
                    string citaEstado, 
                    int emisorId, 
                    string usuarioCreacion, 
                    string citaRazon, 
                    string agenciaOrigen, 
                    string posiciones) {
            object[] results = this.Invoke("CrearCitaProgramada", new object[] {
                        token,
                        citaIdentificacion,
                        citaNombre,
                        citaCorreoElectronico,
                        citaTelefonoCelular,
                        citaTelefonoOficina,
                        citaTelefonoCasa,
                        citaFecha,
                        citaHora,
                        citaTarjeta,
                        citaCuenta,
                        tramiteId,
                        sucursalId,
                        citaSegmentoId,
                        citaEstado,
                        emisorId,
                        usuarioCreacion,
                        citaRazon,
                        agenciaOrigen,
                        posiciones});
            return ((CitaDTO)(results[0]));
        }
        
        /// <remarks/>
        public void CrearCitaProgramadaAsync(
                    string token, 
                    string citaIdentificacion, 
                    string citaNombre, 
                    string citaCorreoElectronico, 
                    string citaTelefonoCelular, 
                    string citaTelefonoOficina, 
                    string citaTelefonoCasa, 
                    System.DateTime citaFecha, 
                    System.DateTime citaHora, 
                    string citaTarjeta, 
                    string citaCuenta, 
                    int tramiteId, 
                    int sucursalId, 
                    string citaSegmentoId, 
                    string citaEstado, 
                    int emisorId, 
                    string usuarioCreacion, 
                    string citaRazon, 
                    string agenciaOrigen, 
                    string posiciones) {
            this.CrearCitaProgramadaAsync(token, citaIdentificacion, citaNombre, citaCorreoElectronico, citaTelefonoCelular, citaTelefonoOficina, citaTelefonoCasa, citaFecha, citaHora, citaTarjeta, citaCuenta, tramiteId, sucursalId, citaSegmentoId, citaEstado, emisorId, usuarioCreacion, citaRazon, agenciaOrigen, posiciones, null);
        }
        
        /// <remarks/>
        public void CrearCitaProgramadaAsync(
                    string token, 
                    string citaIdentificacion, 
                    string citaNombre, 
                    string citaCorreoElectronico, 
                    string citaTelefonoCelular, 
                    string citaTelefonoOficina, 
                    string citaTelefonoCasa, 
                    System.DateTime citaFecha, 
                    System.DateTime citaHora, 
                    string citaTarjeta, 
                    string citaCuenta, 
                    int tramiteId, 
                    int sucursalId, 
                    string citaSegmentoId, 
                    string citaEstado, 
                    int emisorId, 
                    string usuarioCreacion, 
                    string citaRazon, 
                    string agenciaOrigen, 
                    string posiciones, 
                    object userState) {
            if ((this.CrearCitaProgramadaOperationCompleted == null)) {
                this.CrearCitaProgramadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearCitaProgramadaOperationCompleted);
            }
            this.InvokeAsync("CrearCitaProgramada", new object[] {
                        token,
                        citaIdentificacion,
                        citaNombre,
                        citaCorreoElectronico,
                        citaTelefonoCelular,
                        citaTelefonoOficina,
                        citaTelefonoCasa,
                        citaFecha,
                        citaHora,
                        citaTarjeta,
                        citaCuenta,
                        tramiteId,
                        sucursalId,
                        citaSegmentoId,
                        citaEstado,
                        emisorId,
                        usuarioCreacion,
                        citaRazon,
                        agenciaOrigen,
                        posiciones}, this.CrearCitaProgramadaOperationCompleted, userState);
        }
        
        private void OnCrearCitaProgramadaOperationCompleted(object arg) {
            if ((this.CrearCitaProgramadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearCitaProgramadaCompleted(this, new CrearCitaProgramadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarEmailCitaProgramada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskStatus EnviarEmailCitaProgramada(string token, CitaDTO cita) {
            object[] results = this.Invoke("EnviarEmailCitaProgramada", new object[] {
                        token,
                        cita});
            return ((TaskStatus)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarEmailCitaProgramadaAsync(string token, CitaDTO cita) {
            this.EnviarEmailCitaProgramadaAsync(token, cita, null);
        }
        
        /// <remarks/>
        public void EnviarEmailCitaProgramadaAsync(string token, CitaDTO cita, object userState) {
            if ((this.EnviarEmailCitaProgramadaOperationCompleted == null)) {
                this.EnviarEmailCitaProgramadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarEmailCitaProgramadaOperationCompleted);
            }
            this.InvokeAsync("EnviarEmailCitaProgramada", new object[] {
                        token,
                        cita}, this.EnviarEmailCitaProgramadaOperationCompleted, userState);
        }
        
        private void OnEnviarEmailCitaProgramadaOperationCompleted(object arg) {
            if ((this.EnviarEmailCitaProgramadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarEmailCitaProgramadaCompleted(this, new EnviarEmailCitaProgramadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskStatus EnviarEmail(string token, string emailTo, string emailSubject, string message, bool isHTML) {
            object[] results = this.Invoke("EnviarEmail", new object[] {
                        token,
                        emailTo,
                        emailSubject,
                        message,
                        isHTML});
            return ((TaskStatus)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarEmailAsync(string token, string emailTo, string emailSubject, string message, bool isHTML) {
            this.EnviarEmailAsync(token, emailTo, emailSubject, message, isHTML, null);
        }
        
        /// <remarks/>
        public void EnviarEmailAsync(string token, string emailTo, string emailSubject, string message, bool isHTML, object userState) {
            if ((this.EnviarEmailOperationCompleted == null)) {
                this.EnviarEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarEmailOperationCompleted);
            }
            this.InvokeAsync("EnviarEmail", new object[] {
                        token,
                        emailTo,
                        emailSubject,
                        message,
                        isHTML}, this.EnviarEmailOperationCompleted, userState);
        }
        
        private void OnEnviarEmailOperationCompleted(object arg) {
            if ((this.EnviarEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarEmailCompleted(this, new EnviarEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarPorTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TarjetaDTO ConsultarPorTarjeta(string token, string numeroTarjeta) {
            object[] results = this.Invoke("ConsultarPorTarjeta", new object[] {
                        token,
                        numeroTarjeta});
            return ((TarjetaDTO)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPorTarjetaAsync(string token, string numeroTarjeta) {
            this.ConsultarPorTarjetaAsync(token, numeroTarjeta, null);
        }
        
        /// <remarks/>
        public void ConsultarPorTarjetaAsync(string token, string numeroTarjeta, object userState) {
            if ((this.ConsultarPorTarjetaOperationCompleted == null)) {
                this.ConsultarPorTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPorTarjetaOperationCompleted);
            }
            this.InvokeAsync("ConsultarPorTarjeta", new object[] {
                        token,
                        numeroTarjeta}, this.ConsultarPorTarjetaOperationCompleted, userState);
        }
        
        private void OnConsultarPorTarjetaOperationCompleted(object arg) {
            if ((this.ConsultarPorTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPorTarjetaCompleted(this, new ConsultarPorTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfigItemDTO {
        
        private string configIdField;
        
        private string itemIdField;
        
        private string itemDescripcionField;
        
        private string itemAbreviaturaField;
        
        private string itemObservacionField;
        
        private string itemStatusField;
        
        private string itemOrdenField;
        
        private bool hasErrorField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string ConfigId {
            get {
                return this.configIdField;
            }
            set {
                this.configIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDescripcion {
            get {
                return this.itemDescripcionField;
            }
            set {
                this.itemDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public string ItemAbreviatura {
            get {
                return this.itemAbreviaturaField;
            }
            set {
                this.itemAbreviaturaField = value;
            }
        }
        
        /// <remarks/>
        public string ItemObservacion {
            get {
                return this.itemObservacionField;
            }
            set {
                this.itemObservacionField = value;
            }
        }
        
        /// <remarks/>
        public string ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ItemOrden {
            get {
                return this.itemOrdenField;
            }
            set {
                this.itemOrdenField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TarjetaDTO {
        
        private string nombreField;
        
        private string identidadField;
        
        private string telefonoField;
        
        private string emailField;
        
        private string cuentaField;
        
        private string numeroField;
        
        private string razonIdField;
        
        private int emisorIdField;
        
        private string emisorCuentaField;
        
        private string marcaIdField;
        
        private string marcaField;
        
        private string segmentoIdField;
        
        private string segmentoField;
        
        private string productoField;
        
        private string familiaField;
        
        private bool hasErrorField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Identidad {
            get {
                return this.identidadField;
            }
            set {
                this.identidadField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string RazonId {
            get {
                return this.razonIdField;
            }
            set {
                this.razonIdField = value;
            }
        }
        
        /// <remarks/>
        public int EmisorId {
            get {
                return this.emisorIdField;
            }
            set {
                this.emisorIdField = value;
            }
        }
        
        /// <remarks/>
        public string EmisorCuenta {
            get {
                return this.emisorCuentaField;
            }
            set {
                this.emisorCuentaField = value;
            }
        }
        
        /// <remarks/>
        public string MarcaId {
            get {
                return this.marcaIdField;
            }
            set {
                this.marcaIdField = value;
            }
        }
        
        /// <remarks/>
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        public string SegmentoId {
            get {
                return this.segmentoIdField;
            }
            set {
                this.segmentoIdField = value;
            }
        }
        
        /// <remarks/>
        public string Segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
            }
        }
        
        /// <remarks/>
        public string Producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        public string Familia {
            get {
                return this.familiaField;
            }
            set {
                this.familiaField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaskStatus {
        
        private bool hasErrorField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CitaDTO {
        
        private string nombreField;
        
        private string identidadField;
        
        private string telefonoField;
        
        private string emailField;
        
        private int idField;
        
        private System.DateTime fechaField;
        
        private System.DateTime horaField;
        
        private string ticketField;
        
        private string estadoField;
        
        private string posicionNombreField;
        
        private string prioridadNombreField;
        
        private int sucursalIdField;
        
        private string sucursalNombreField;
        
        private string marcaIdField;
        
        private string segmentoIdField;
        
        private string productoField;
        
        private string familiaField;
        
        private string razonIdField;
        
        private string razonField;
        
        private bool hasErrorField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Identidad {
            get {
                return this.identidadField;
            }
            set {
                this.identidadField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public string Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string PosicionNombre {
            get {
                return this.posicionNombreField;
            }
            set {
                this.posicionNombreField = value;
            }
        }
        
        /// <remarks/>
        public string PrioridadNombre {
            get {
                return this.prioridadNombreField;
            }
            set {
                this.prioridadNombreField = value;
            }
        }
        
        /// <remarks/>
        public int SucursalId {
            get {
                return this.sucursalIdField;
            }
            set {
                this.sucursalIdField = value;
            }
        }
        
        /// <remarks/>
        public string SucursalNombre {
            get {
                return this.sucursalNombreField;
            }
            set {
                this.sucursalNombreField = value;
            }
        }
        
        /// <remarks/>
        public string MarcaId {
            get {
                return this.marcaIdField;
            }
            set {
                this.marcaIdField = value;
            }
        }
        
        /// <remarks/>
        public string SegmentoId {
            get {
                return this.segmentoIdField;
            }
            set {
                this.segmentoIdField = value;
            }
        }
        
        /// <remarks/>
        public string Producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        public string Familia {
            get {
                return this.familiaField;
            }
            set {
                this.familiaField = value;
            }
        }
        
        /// <remarks/>
        public string RazonId {
            get {
                return this.razonIdField;
            }
            set {
                this.razonIdField = value;
            }
        }
        
        /// <remarks/>
        public string Razon {
            get {
                return this.razonField;
            }
            set {
                this.razonField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HorarioDTO {
        
        private int sucursalIdField;
        
        private string idField;
        
        private bool esLaboralField;
        
        private string horaInicioField;
        
        private string horaFinalField;
        
        private int horaInicioEnMinutosField;
        
        private int horaFinalEnMinutosField;
        
        private bool esCorridoField;
        
        private string posicionesField;
        
        private bool hasErrorField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int SucursalId {
            get {
                return this.sucursalIdField;
            }
            set {
                this.sucursalIdField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool EsLaboral {
            get {
                return this.esLaboralField;
            }
            set {
                this.esLaboralField = value;
            }
        }
        
        /// <remarks/>
        public string HoraInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
            }
        }
        
        /// <remarks/>
        public string HoraFinal {
            get {
                return this.horaFinalField;
            }
            set {
                this.horaFinalField = value;
            }
        }
        
        /// <remarks/>
        public int HoraInicioEnMinutos {
            get {
                return this.horaInicioEnMinutosField;
            }
            set {
                this.horaInicioEnMinutosField = value;
            }
        }
        
        /// <remarks/>
        public int HoraFinalEnMinutos {
            get {
                return this.horaFinalEnMinutosField;
            }
            set {
                this.horaFinalEnMinutosField = value;
            }
        }
        
        /// <remarks/>
        public bool EsCorrido {
            get {
                return this.esCorridoField;
            }
            set {
                this.esCorridoField = value;
            }
        }
        
        /// <remarks/>
        public string Posiciones {
            get {
                return this.posicionesField;
            }
            set {
                this.posicionesField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SucursalDTO {
        
        private int idField;
        
        private string nombreField;
        
        private string direccionField;
        
        private bool hasErrorField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoRazonDTO {
        
        private int idField;
        
        private string descripcionField;
        
        private string abreviaturaField;
        
        private string autoservicioField;
        
        private string statusField;
        
        private bool hasErrorField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
            }
        }
        
        /// <remarks/>
        public string Autoservicio {
            get {
                return this.autoservicioField;
            }
            set {
                this.autoservicioField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarListasDeConfiguracionCompletedEventHandler(object sender, ConsultarListasDeConfiguracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarListasDeConfiguracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarListasDeConfiguracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfigItemDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfigItemDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarTiposRazonCompletedEventHandler(object sender, ConsultarTiposRazonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarTiposRazonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarTiposRazonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoRazonDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoRazonDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarCentrosDeAtencionCompletedEventHandler(object sender, ConsultarCentrosDeAtencionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCentrosDeAtencionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCentrosDeAtencionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SucursalDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SucursalDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarCentrosDeAtencionPorSegmentoCompletedEventHandler(object sender, ConsultarCentrosDeAtencionPorSegmentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCentrosDeAtencionPorSegmentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCentrosDeAtencionPorSegmentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SucursalDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SucursalDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarHorariosDeAtencionCompletedEventHandler(object sender, ConsultarHorariosDeAtencionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarHorariosDeAtencionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarHorariosDeAtencionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HorarioDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HorarioDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarSucursalCompletedEventHandler(object sender, ConsultarSucursalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarSucursalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarSucursalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SucursalDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SucursalDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarCitaPorTicketCompletedEventHandler(object sender, ConsultarCitaPorTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCitaPorTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCitaPorTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CitaDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CitaDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarCitaPorTarjetaCompletedEventHandler(object sender, ConsultarCitaPorTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCitaPorTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCitaPorTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CitaDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CitaDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConfirmarCitaCompletedEventHandler(object sender, ConfirmarCitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarCitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarCitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearCitaWalkInCompletedEventHandler(object sender, CrearCitaWalkInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearCitaWalkInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearCitaWalkInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CitaDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CitaDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearCitaProgramadaCompletedEventHandler(object sender, CrearCitaProgramadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearCitaProgramadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearCitaProgramadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CitaDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CitaDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EnviarEmailCitaProgramadaCompletedEventHandler(object sender, EnviarEmailCitaProgramadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarEmailCitaProgramadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarEmailCitaProgramadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EnviarEmailCompletedEventHandler(object sender, EnviarEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarPorTarjetaCompletedEventHandler(object sender, ConsultarPorTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPorTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPorTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TarjetaDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TarjetaDTO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591